<?
include(dirname(__FILE__) . "/../application.php");

$tablas = array(
"ases",
"barrios",
"borrar",
"cargos",
"categorias_informes",
"centros",
"ciudades",
"comunas",
"cuartelillos",
"cuartelillos_personas",
"departamentos",
"dotaciones",
"elementos_dotaciones",
"empresas",
"errores",
"estados_personas",
"estados_vehiculos",
"eventos",
"frecuencias_bolsas",
"frecuencias_desplazamientos",
"frecuencias_operarios",
"historico_recorrido",
"informes",
"lugares_descargue",
"marcas_vehiculos",
"micros",
"micros_frecuencia",
"micros_segmentos",
"micros_tipos_vehiculos",
"municipios",
"novedades",
"peajes",
"peajes_micros",
"peajes_vigencias",
"personas",
"personas_cargos",
"personas_centros",
"personas_servicios",
"personas_tareas",
"prueba",
"referencias",
"servicios",
"tareas",
"tipos_novedades",
"tipos_residuos",
"tipos_segmentos",
"tipos_vehiculos",
"tipos_vehiculos_servicios",
"tipos_vehiculos_sui",
"turnos",
"unidades",
"vehiculos",
"bar.movimientos",
"bar.movimientos_bolsas",
"bar.movimientos_personas",
"bar.tipos_bolsas",
"llta.dimensiones",
"llta.estados",
"llta.estados_reencauches",
"llta.estados_tiposmovimiento",
"llta.llantas",
"llta.llantas_historico_disenio",
"llta.marcas",
"llta.movimientos",
"llta.proveedores",
"llta.proveedores_centros",
"llta.subtipos_movimientos",
"llta.tipos_llantas",
"llta.tipos_movimientos",
"mtto.bodegas",
"mtto.ele_tipos",
"mtto.elementos",
"mtto.elementos_centros",
"mtto.elementos_existencias",
"mtto.equipos",
"mtto.equipos_archivos",
"mtto.estados_ordenes_trabajo",
"mtto.excepciones_diarias",
"mtto.excepciones_periodos",
"mtto.frecuencias",
"mtto.grupos",
"mtto.inspecciones",
"mtto.inspecciones_items",
"mtto.items",
"mtto.motivos",
"mtto.ordenes_rutinas_mediciones",
"mtto.ordenes_trabajo",
"mtto.ordenes_trabajo_actividades",
"mtto.ordenes_trabajo_actividades_cargos",
"mtto.ordenes_trabajo_elementos",
"mtto.ordenes_trabajo_fechas_programadas",
"mtto.ordenes_trabajo_origen",
"mtto.ordenes_trabajo_talleres",
"mtto.prioridades",
"mtto.rutinas",
"mtto.rutinas_actividades",
"mtto.rutinas_actividades_cargos",
"mtto.rutinas_centros",
"mtto.rutinas_elementos",
"mtto.rutinas_mediciones",
"mtto.rutinas_primera_vez",
"mtto.rutinas_talleres",
"mtto.sistemas",
"mtto.tipos",
"mtto.unidades",
"mtto.variables_mtto",
"rec.apoyos",
"rec.apoyos_movimientos ",
"rec.desplazamientos",
"rec.movimientos",
"rec.movimientos_personas ",
"rec.movimientos_pesos",
"rec.tipos_desplazamientos");

foreach($tablas as $tl)
{
	$db->sql_query("vacuum ANALYZE ".$tl);
	file_put_contents($CFG->dirroot.'/crons/log_va.log',"\n tabla : ".$tl." : ".date("Y-m-d H:i:s"),FILE_APPEND);
}

//mail("luisa@apli-k.com", "vacuum bd aida", "se ejecuto el cron");
file_put_contents($CFG->dirroot.'/crons/log_va.log',"\nHECHO ".date("Y-m-d H:i:s"),FILE_APPEND);
?>
